import 'package:first_flutter_app/shared/theme/lacuna_theme.dart';
import 'package:flutter/material.dart';

const _calm = LacunaTheme(
  variant: LacunaThemeVariant.calm,
  displayName: 'Calm',
  tagline: 'soft violet dusk',
  fontName: 'Inter',
  radiusScale: 1.0,
  grainOpacity: 0.04,
  scallop: ScallopConfig(lobes: 12, depth: 0.07),
  surfaceStyle: SurfaceStyle.frosted,
  backgroundMode: BackgroundMode.gradient,
  bgGradient: [Color(0xFF0B0A12), Color(0xFF15101F), Color(0xFF06060B)],
  blurSigma: 9,
  specularOpacity: 0.06,
  depthShadow: 0.3,
  motionScale: 1.0,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF06060B),
    bgBase: Color(0xFF0B0A12),
    surface1: Color(0xFF12111B),
    surface2: Color(0xFF181624),
    surface3: Color(0xFF221F30),
    borderSubtle: Color(0xFF1A1826),
    borderHairline: Color(0x14FFFFFF),
    textPrimary: Color(0xFFF1ECFA),
    textSecondary: Color(0xFF9990AE),
    textTertiary: Color(0xFF625A78),
    textDisabled: Color(0xFF3A3550),
    accent: Color(0xFFB7A6F0),
    accentSoft: Color(0xFF8C7BD9),
    accentDeep: Color(0xFF6A57BC),
    accentGlow: Color(0x40B7A6F0),
    upvote: Color(0xFFB7A6F0),
    downvote: Color(0xFFD17B8E),
  ),
);

const _industrial = LacunaTheme(
  variant: LacunaThemeVariant.industrial,
  displayName: 'Industrial',
  tagline: 'steel, concrete, rust',
  fontName: 'Space Mono',
  radiusScale: 0.3,
  grainOpacity: 0.08,
  scallop: ScallopConfig(lobes: 6, depth: 0.0),
  surfaceStyle: SurfaceStyle.solid,
  backgroundMode: BackgroundMode.flat,
  bgGradient: [Color(0xFF141414), Color(0xFF141414)],
  blurSigma: 0,
  specularOpacity: 0,
  depthShadow: 0.6,
  motionScale: 0.6,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF0A0A0A),
    bgBase: Color(0xFF141414),
    surface1: Color(0xFF1C1C1C),
    surface2: Color(0xFF242424),
    surface3: Color(0xFF2E2E2E),
    borderSubtle: Color(0xFF2A2A2A),
    borderHairline: Color(0x1FFFFFFF),
    textPrimary: Color(0xFFF2E9DE),
    textSecondary: Color(0xFF9A9289),
    textTertiary: Color(0xFF6B6560),
    textDisabled: Color(0xFF3E3B38),
    accent: Color(0xFFE07B3F),
    accentSoft: Color(0xFFB55E2D),
    accentDeep: Color(0xFF8F471F),
    accentGlow: Color(0x40E07B3F),
    upvote: Color(0xFFE07B3F),
    downvote: Color(0xFF7E7E7E),
  ),
);

const _space = LacunaTheme(
  variant: LacunaThemeVariant.space,
  displayName: 'Space',
  tagline: 'cosmic quiet',
  fontName: 'Orbitron',
  radiusScale: 1.5,
  grainOpacity: 0.02,
  scallop: ScallopConfig(lobes: 0, depth: 0),
  surfaceStyle: SurfaceStyle.frosted,
  backgroundMode: BackgroundMode.flat,
  bgGradient: [Color(0xFF050D24), Color(0xFF050D24), Color(0xFF050D24)],
  blurSigma: 10,
  specularOpacity: 0.12,
  depthShadow: 0.25,
  motionScale: 0.8,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF000510),
    bgBase: Color(0xFF050D24),
    surface1: Color(0xFF0A1533),
    surface2: Color(0xFF111E44),
    surface3: Color(0xFF1A2A5A),
    borderSubtle: Color(0xFF152240),
    borderHairline: Color(0x1FB8DDFF),
    textPrimary: Color(0xFFE8EEFF),
    textSecondary: Color(0xFF8B9AC0),
    textTertiary: Color(0xFF5A6688),
    textDisabled: Color(0xFF394266),
    accent: Color(0xFF7DA3FF),
    accentSoft: Color(0xFF5D82D9),
    accentDeep: Color(0xFF3A5FB5),
    accentGlow: Color(0x507DA3FF),
    upvote: Color(0xFF7DA3FF),
    downvote: Color(0xFFFF7B9C),
  ),
);

const _effervescent = LacunaTheme(
  variant: LacunaThemeVariant.effervescent,
  displayName: 'Effervescent',
  tagline: 'soda pop sunrise',
  fontName: 'Quicksand',
  radiusScale: 1.8,
  grainOpacity: 0.02,
  scallop: ScallopConfig(lobes: 16, depth: 0.15),
  surfaceStyle: SurfaceStyle.paper,
  backgroundMode: BackgroundMode.gradient,
  bgGradient: [Color(0xFFFFF2F5), Color(0xFFFFE8EE), Color(0xFFFFDCE4)],
  blurSigma: 8,
  specularOpacity: 0.08,
  depthShadow: 0.3,
  motionScale: 1.3,
  palette: ColorPalette(
    brightness: Brightness.light,
    bgDeep: Color(0xFFFFE8EE),
    bgBase: Color(0xFFFFF2F5),
    surface1: Color(0xFFFFFFFF),
    surface2: Color(0xFFFFF8FA),
    surface3: Color(0xFFFFEFF4),
    borderSubtle: Color(0xFFFFDCE4),
    borderHairline: Color(0x14000000),
    textPrimary: Color(0xFF2E1D26),
    textSecondary: Color(0xFF74566A),
    textTertiary: Color(0xFFAE8FA2),
    textDisabled: Color(0xFFD7C0CC),
    accent: Color(0xFFFF9AC2),
    accentSoft: Color(0xFFFFB8D4),
    accentDeep: Color(0xFFD4628E),
    accentGlow: Color(0x50FF9AC2),
    upvote: Color(0xFFFF9AC2),
    downvote: Color(0xFFF2896B),
  ),
);

const _translucent = LacunaTheme(
  variant: LacunaThemeVariant.translucent,
  displayName: 'Translucent',
  tagline: 'ghosts between panes',
  fontName: 'Inter',
  radiusScale: 1.2,
  grainOpacity: 0.02,
  scallop: ScallopConfig(lobes: 8, depth: 0.05),
  surfaceStyle: SurfaceStyle.liquidGlass,
  backgroundMode: BackgroundMode.aurora,
  bgGradient: [Color(0xFF14161C), Color(0xFF1C1F28), Color(0xFF2C303D)],
  blurSigma: 14,
  specularOpacity: 0.18,
  depthShadow: 0.2,
  motionScale: 1.0,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF14161C),
    bgBase: Color(0xFF1C1F28),
    surface1: Color(0x661C1F28),
    surface2: Color(0x802C303D),
    surface3: Color(0x993A3F4F),
    borderSubtle: Color(0x33FFFFFF),
    borderHairline: Color(0x1FFFFFFF),
    textPrimary: Color(0xFFEDEEF2),
    textSecondary: Color(0xB3D0D3DC),
    textTertiary: Color(0x80A0A4AE),
    textDisabled: Color(0x4DFFFFFF),
    accent: Color(0xB3C8D8FF),
    accentSoft: Color(0x80A0BAFF),
    accentDeep: Color(0xFF6B8BC8),
    accentGlow: Color(0x40C8D8FF),
    upvote: Color(0xB3C8D8FF),
    downvote: Color(0xB3FFB8C8),
  ),
);

const _glass = LacunaTheme(
  variant: LacunaThemeVariant.glass,
  displayName: 'Glass',
  tagline: 'lit ice, drifting hues',
  fontName: 'Inter',
  radiusScale: 1.4,
  grainOpacity: 0.0,
  scallop: ScallopConfig(lobes: 8, depth: 0.02),
  surfaceStyle: SurfaceStyle.liquidGlass,
  backgroundMode: BackgroundMode.iosGlass,
  bgGradient: [Color(0xFFFAFCFE), Color(0xFFF2F6FA), Color(0xFFE8EFF6)],
  blurSigma: 20,
  specularOpacity: 0.55,
  depthShadow: 0.55,
  motionScale: 0.85,
  palette: ColorPalette(
    brightness: Brightness.light,
    bgDeep: Color(0xFFE3EEF6),
    bgBase: Color(0xFFEFF6FB),
    surface1: Color(0xFFFFFFFF),
    surface2: Color(0xFFF2F8FC),
    surface3: Color(0xFFE0EDF5),
    borderSubtle: Color(0xFFD6E5F0),
    borderHairline: Color(0x29133A5C),
    textPrimary: Color(0xFF0E2236),
    textSecondary: Color(0xFF3D5670),
    textTertiary: Color(0xFF6B86A0),
    textDisabled: Color(0xFFA8BDD0),
    accent: Color(0xFF1E9CFF),
    accentSoft: Color(0xFF6FBFFF),
    accentDeep: Color(0xFF0A6CCB),
    accentGlow: Color(0x501E9CFF),
    upvote: Color(0xFF1E9CFF),
    downvote: Color(0xFFFF6F8E),
  ),
);

const _white = LacunaTheme(
  variant: LacunaThemeVariant.white,
  displayName: 'White',
  tagline: 'pure gallery',
  fontName: 'Inter',
  radiusScale: 0.5,
  grainOpacity: 0.0,
  scallop: ScallopConfig(lobes: 0, depth: 0),
  surfaceStyle: SurfaceStyle.solid,
  backgroundMode: BackgroundMode.flat,
  bgGradient: [Color(0xFFFAFAFA), Color(0xFFFAFAFA)],
  blurSigma: 0,
  specularOpacity: 0,
  depthShadow: 0.4,
  motionScale: 1.0,
  palette: ColorPalette(
    brightness: Brightness.light,
    bgDeep: Color(0xFFFFFFFF),
    bgBase: Color(0xFFFAFAFA),
    surface1: Color(0xFFFFFFFF),
    surface2: Color(0xFFF4F4F4),
    surface3: Color(0xFFECECEC),
    borderSubtle: Color(0xFFE4E4E4),
    borderHairline: Color(0x14000000),
    textPrimary: Color(0xFF1A1A1A),
    textSecondary: Color(0xFF5E5E5E),
    textTertiary: Color(0xFF9A9A9A),
    textDisabled: Color(0xFFCFCFCF),
    accent: Color(0xFF000000),
    accentSoft: Color(0xFF333333),
    accentDeep: Color(0xFF000000),
    accentGlow: Color(0x1F000000),
    upvote: Color(0xFF000000),
    downvote: Color(0xFFC43B3B),
  ),
);

const _monotone = LacunaTheme(
  variant: LacunaThemeVariant.monotone,
  displayName: 'Monotone',
  tagline: 'greys and nothing else',
  fontName: 'IBM Plex Mono',
  radiusScale: 0.2,
  grainOpacity: 0.05,
  scallop: ScallopConfig(lobes: 4, depth: 0.03),
  surfaceStyle: SurfaceStyle.solid,
  backgroundMode: BackgroundMode.noise,
  bgGradient: [Color(0xFF0A0A0A), Color(0xFF0A0A0A)],
  blurSigma: 0,
  specularOpacity: 0,
  depthShadow: 0.5,
  motionScale: 0.9,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF000000),
    bgBase: Color(0xFF0A0A0A),
    surface1: Color(0xFF141414),
    surface2: Color(0xFF1F1F1F),
    surface3: Color(0xFF2B2B2B),
    borderSubtle: Color(0xFF1C1C1C),
    borderHairline: Color(0x1FFFFFFF),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFBABABA),
    textTertiary: Color(0xFF7A7A7A),
    textDisabled: Color(0xFF4A4A4A),
    accent: Color(0xFFFFFFFF),
    accentSoft: Color(0xFFBABABA),
    accentDeep: Color(0xFF7A7A7A),
    accentGlow: Color(0x30FFFFFF),
    upvote: Color(0xFFFFFFFF),
    downvote: Color(0xFF5A5A5A),
  ),
);

const _zen = LacunaTheme(
  variant: LacunaThemeVariant.zen,
  displayName: 'Zen',
  tagline: 'moss, stone, tea',
  fontName: 'Lora',
  radiusScale: 1.3,
  grainOpacity: 0.06,
  scallop: ScallopConfig(lobes: 6, depth: 0.12),
  surfaceStyle: SurfaceStyle.paper,
  backgroundMode: BackgroundMode.gradient,
  bgGradient: [Color(0xFF2A241D), Color(0xFF342D24), Color(0xFF1F1A14)],
  blurSigma: 8,
  specularOpacity: 0.04,
  depthShadow: 0.3,
  motionScale: 0.7,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF1F1A14),
    bgBase: Color(0xFF2A241D),
    surface1: Color(0xFF342D24),
    surface2: Color(0xFF3F362B),
    surface3: Color(0xFF4B4135),
    borderSubtle: Color(0xFF2F281F),
    borderHairline: Color(0x1FE8DDC8),
    textPrimary: Color(0xFFE8DDC8),
    textSecondary: Color(0xFFAEA28C),
    textTertiary: Color(0xFF7A7060),
    textDisabled: Color(0xFF4E4738),
    accent: Color(0xFFAFC7A8),
    accentSoft: Color(0xFF8EAA85),
    accentDeep: Color(0xFF698964),
    accentGlow: Color(0x40AFC7A8),
    upvote: Color(0xFFAFC7A8),
    downvote: Color(0xFFC79982),
  ),
);

const _rage = LacunaTheme(
  variant: LacunaThemeVariant.rage,
  displayName: 'Rage',
  tagline: 'teeth bared, eyes open',
  fontName: 'Bebas Neue',
  radiusScale: 0.1,
  grainOpacity: 0.12,
  scallop: ScallopConfig(lobes: 24, depth: 0.25),
  surfaceStyle: SurfaceStyle.solid,
  backgroundMode: BackgroundMode.orbs,
  bgGradient: [Color(0xFF0A0000), Color(0xFF000000), Color(0xFF220808)],
  blurSigma: 0,
  specularOpacity: 0,
  depthShadow: 0.7,
  motionScale: 1.5,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF000000),
    bgBase: Color(0xFF0A0000),
    surface1: Color(0xFF140505),
    surface2: Color(0xFF220808),
    surface3: Color(0xFF330C0C),
    borderSubtle: Color(0xFF2A0A0A),
    borderHairline: Color(0x30FF2B2B),
    textPrimary: Color(0xFFF5F5F5),
    textSecondary: Color(0xFFBFA8A8),
    textTertiary: Color(0xFF7F6868),
    textDisabled: Color(0xFF4A3838),
    accent: Color(0xFFE63946),
    accentSoft: Color(0xFFC02030),
    accentDeep: Color(0xFF8A1520),
    accentGlow: Color(0x60E63946),
    upvote: Color(0xFFE63946),
    downvote: Color(0xFF5A5A5A),
  ),
);

const _barbaric = LacunaTheme(
  variant: LacunaThemeVariant.barbaric,
  displayName: 'Barbaric',
  tagline: 'ember, leather, bone',
  fontName: 'Cinzel',
  radiusScale: 0.4,
  grainOpacity: 0.14,
  scallop: ScallopConfig(lobes: 5, depth: 0.3),
  surfaceStyle: SurfaceStyle.paper,
  backgroundMode: BackgroundMode.noise,
  bgGradient: [Color(0xFF2A1A10), Color(0xFF352218), Color(0xFF1A0E08)],
  blurSigma: 4,
  specularOpacity: 0.02,
  depthShadow: 0.5,
  motionScale: 0.8,
  palette: ColorPalette(
    brightness: Brightness.dark,
    bgDeep: Color(0xFF1A0E08),
    bgBase: Color(0xFF2A1A10),
    surface1: Color(0xFF352218),
    surface2: Color(0xFF3F2A1F),
    surface3: Color(0xFF4C3526),
    borderSubtle: Color(0xFF2B1C14),
    borderHairline: Color(0x1FEDDFCC),
    textPrimary: Color(0xFFEDDFCC),
    textSecondary: Color(0xFFB29882),
    textTertiary: Color(0xFF7F6A58),
    textDisabled: Color(0xFF4F4238),
    accent: Color(0xFFE8742C),
    accentSoft: Color(0xFFC45A1C),
    accentDeep: Color(0xFF8F3F10),
    accentGlow: Color(0x60E8742C),
    upvote: Color(0xFFE8742C),
    downvote: Color(0xFF8A4A3A),
  ),
);

const lacunaThemes = <LacunaThemeVariant, LacunaTheme>{
  LacunaThemeVariant.calm: _calm,
  LacunaThemeVariant.industrial: _industrial,
  LacunaThemeVariant.space: _space,
  LacunaThemeVariant.effervescent: _effervescent,
  LacunaThemeVariant.translucent: _translucent,
  LacunaThemeVariant.glass: _glass,
  LacunaThemeVariant.white: _white,
  LacunaThemeVariant.monotone: _monotone,
  LacunaThemeVariant.zen: _zen,
  LacunaThemeVariant.rage: _rage,
  LacunaThemeVariant.barbaric: _barbaric,
};

LacunaTheme themeFor(LacunaThemeVariant variant) =>
    lacunaThemes[variant] ?? _calm;
